# Generated by Django 4.0.4 on 2022-05-11 05:08

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eco_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eco_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Ecosystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecosystem_name', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=300)),
                ('template_name', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Are there enabling policies and practices?'), (2, 'Existing infrastructure to support ecosystems?'), (3, 'Leaders, Partnerships and Allies?'), (4, 'Public and/or Political Will?'), (5, 'Familiarity and Commitment to the Ecosystems Vision in the community?'), (6, 'Strong Community Partnerships?'), (7, 'Urgency to address the issues at hand in new and different ways?'), (8, 'Youth led efforts and organizations?'), (9, 'Learner Centered Sites and organizations?'), (10, 'Coordinator Role of individual or organization?')], max_length=20, null=True)),
            ],
        ),
    ]
