# Generated by Django 4.0.4 on 2022-05-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eco_list',
            name='template_conditions',
            field=models.TextField(blank=True),
        ),
    ]
